language: python
python:
  - '2.6'
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
matrix:
  include:
    # Force Ubuntu 14 for Python 2.6 (default=16)
    - python: 2.6
      dist: trusty
      sudo: true

install:
  - pip install -e .[test]

script:
  - nosetests
